customhost = "employee.c9ripedo7am8.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "yaphongkiat-employee"
customregion = "us-east-1b"
